"""Regression fence for the 2026-06-04 training-flow rework (P2).

Customer decision locked for this phase:

  When a training session is started from a ``reference_persona`` (the gallery
  of approved client dossiers), the DOSSIER is the SINGLE source of the
  client's identity. The autogenerated ``ClientProfile`` row still exists in
  the DB (it is needed for the FK and for scoring), but NONE of its random
  identity — name, debt, income, fears, soft-spot — may surface either:

    * in the LLM system prompt (``_build_client_profile_prompt``), nor
    * in the WS payloads that drive the visible session header / typing
      indicator / overlay subtitle / call screen (``character_name`` and the
      ``client_card.full_name`` shipped with ``session.started`` /
      ``session.resumed``).

  Otherwise the AI introduces itself as «Ирина Петрова» (dossier) while the
  UI labels the session «Сидоров» (random generator) — the double identity
  the rework exists to eliminate.

A non-persona session (empty / missing ``persona_brief``) must behave exactly
as before: the generated identity drives both the prompt and the UI.

Each test below FAILS on the pre-P2 code:

  * ``_build_client_profile_prompt`` pre-P2 had no ``_is_persona_session``
    branch — it ALWAYS emitted ``Имя: {profile.full_name}`` and the debt line,
    so the random «Сидоров» / debt leaked into the persona prompt.
  * ``_persona_name_from_params`` did not exist — the three WS ship sites took
    ``client_card.full_name`` unconditionally, leaking the random name to the
    session header on every persona session.
  * The persona name-pin branch in ``_generate_character_reply`` did not
    exist — the pin used ``state["client_name"]`` (the random ClientProfile
    name) even for persona sessions.

These are unit-level (no DB) so they run in the blocking CI scope.
"""
from __future__ import annotations

import ast
import inspect
from types import SimpleNamespace

from app.ws import training as ws_training
from app.ws.training import (
    _build_client_profile_prompt,
    _persona_name_from_params,
)


# ──────────────────────────────────────────────────────────────────────────
# Test fixtures: a RANDOM generated ClientProfile vs. the persona dossier.
# The names/numbers are deliberately disjoint so a leak is unambiguous:
#   random generator → «Сидоров», debt 999 999 ₽
#   dossier/persona  → «Ирина Петрова», debt ~1,3 млн ₽
# ──────────────────────────────────────────────────────────────────────────

_RANDOM_NAME = "Пётр Сидоров"
_RANDOM_DEBT = 999_999
_RANDOM_INCOME = 123_456
_RANDOM_FEAR = "СЛУЧАЙНЫЙ_СТРАХ_ГЕНЕРАТОРА"
_RANDOM_SOFT_SPOT = "СЛУЧАЙНАЯ_МЯГКАЯ_ТОЧКА"

_PERSONA_NAME = "Ирина Петрова"
# Client-facts portion of the dossier (what split_dossier feeds into
# custom_params["persona_brief"] — everything BEFORE «ЧТО ЮРИСТ ОБЯЗАН …»).
_PERSONA_BRIEF = (
    "ДОСЬЕ КЛИЕНТА (физлицо, ФЗ-127).\n"
    "\n"
    "Кто: Ирина Петрова, 36 лет, бухгалтер. Замужем, двое детей. "
    "Обратилась сама после звонка коллекторов — в тревоге и стыде.\n"
    "\n"
    "Состав долга: ~1,3 млн ₽ необеспеченного потребительского долга в двух "
    "банках и одной МФО. Квартира — единственное жильё — в ИПОТЕКЕ (залог)."
)


def _random_profile() -> SimpleNamespace:
    """The autogenerated ClientProfile — its identity must be suppressed in
    persona mode but emitted verbatim in normal mode."""
    return SimpleNamespace(
        full_name=_RANDOM_NAME,
        age=44,
        city="Саратов",
        fears=[_RANDOM_FEAR, "потеря работы"],
        soft_spot=_RANDOM_SOFT_SPOT,
        breaking_point="триггер согласия",
        total_debt=_RANDOM_DEBT,
        income=_RANDOM_INCOME,
        income_type="официальный",
        trust_level=4,
        resistance_level=6,
        hidden_objections=["скрытое возражение"],
    )


def _persona_ambient() -> dict:
    """custom_params for a persona session: persona_brief + persona_name pinned
    at API start (training.py:802-805) plus an atmosphere preset that must
    survive in BOTH modes (it shapes the moment, not the identity)."""
    return {
        "persona_brief": _PERSONA_BRIEF,
        "persona_name": _PERSONA_NAME,
        "emotion_preset": "anxious",
        "time_of_day": "evening",
    }


# ──────────────────────────────────────────────────────────────────────────
# (A) Prompt content — persona mode suppresses the random identity
# ──────────────────────────────────────────────────────────────────────────


def test_persona_prompt_omits_random_generated_name_and_debt():
    """Pre-P2 FAIL: ``_build_client_profile_prompt`` always emitted
    ``Имя: {profile.full_name}`` and the debt/income/fears lines, so the random
    «Сидоров» / 999 999 ₽ leaked into the persona prompt alongside the dossier.
    """
    prompt = _build_client_profile_prompt(_random_profile(), ambient_ctx=_persona_ambient())

    # The random generated identity must NOT appear anywhere.
    assert _RANDOM_NAME not in prompt
    assert "Сидоров" not in prompt
    assert f"{_RANDOM_DEBT:,.0f}" not in prompt
    assert "999,999" not in prompt and "999999" not in prompt
    assert f"{_RANDOM_INCOME:,.0f}" not in prompt
    assert _RANDOM_FEAR not in prompt
    assert _RANDOM_SOFT_SPOT not in prompt
    # The generated "Контекст клиента" identity header must be gone too.
    assert "## Контекст клиента" not in prompt


def test_persona_prompt_carries_the_dossier_identity():
    """The dossier «Кто ты» block — the single authoritative identity — must be
    present and name the persona, so the prompt is not left identity-less."""
    prompt = _build_client_profile_prompt(_random_profile(), ambient_ctx=_persona_ambient())

    assert "## Кто ты (досье клиента)" in prompt
    assert _PERSONA_NAME in prompt            # «Ирина Петрова» from the dossier
    assert "Состав долга: ~1,3 млн ₽" in prompt
    # And it stays a debtor, not a lawyer.
    assert "Ты — КЛИЕНТ-должник" in prompt


def test_persona_prompt_keeps_atmosphere_block():
    """The «## Атмосфера» preset (emotion/time/noise) must survive in persona
    mode — it shapes the *moment* of the call, not the permanent identity, and
    must NOT be suppressed along with the random identity."""
    prompt = _build_client_profile_prompt(_random_profile(), ambient_ctx=_persona_ambient())
    assert "## Атмосфера" in prompt
    assert "тревожное" in prompt              # emotion_preset=anxious label
    assert "вечер" in prompt                  # time_of_day=evening label


# ──────────────────────────────────────────────────────────────────────────
# (B) Prompt content — non-persona mode is unchanged (no regression)
# ──────────────────────────────────────────────────────────────────────────


def test_non_persona_prompt_emits_generated_identity_as_before():
    """With an empty / missing persona_brief the generated identity drives the
    prompt exactly as pre-P2 — name, debt, income, fears, soft-spot all present,
    and no dossier block is injected."""
    prompt = _build_client_profile_prompt(
        _random_profile(),
        ambient_ctx={"emotion_preset": "anxious"},  # atmosphere only, no persona
    )
    assert "## Контекст клиента" in prompt
    assert _RANDOM_NAME in prompt
    assert f"{_RANDOM_DEBT:,.0f}" in prompt
    assert _RANDOM_FEAR in prompt
    assert _RANDOM_SOFT_SPOT in prompt
    # No dossier identity in normal mode.
    assert "## Кто ты (досье клиента)" not in prompt


def test_empty_persona_brief_is_treated_as_non_persona():
    """A blank/whitespace persona_brief must not flip the session into persona
    mode — the generated identity is still emitted (defensive: a stray empty
    key in custom_params must not blank the client)."""
    for blank in ("", "   ", "\n\t"):
        prompt = _build_client_profile_prompt(
            _random_profile(),
            ambient_ctx={"persona_brief": blank, "persona_name": _PERSONA_NAME},
        )
        assert "## Контекст клиента" in prompt
        assert _RANDOM_NAME in prompt
        assert "## Кто ты (досье клиента)" not in prompt


# ──────────────────────────────────────────────────────────────────────────
# (C) UI display name — the three WS ship sites prefer the persona name
# ──────────────────────────────────────────────────────────────────────────
# ``_persona_name_from_params`` is the single helper used at all three sites
# (session.started fresh, session.started resume, session.resumed confirm) to
# override ``character_name`` and the shipped ``client_card.full_name``. It is
# the unit that fences the on-screen double-identity leak.


def test_display_helper_returns_persona_name_for_persona_session():
    """Pre-P2 FAIL: the helper did not exist; sites used client_card.full_name
    (the random «Сидоров») unconditionally. It must now return the pinned
    persona name so the UI header matches the AI's self-introduction."""
    assert _persona_name_from_params(_persona_ambient()) == _PERSONA_NAME


def test_display_helper_empty_for_non_persona_session():
    """No persona_brief → empty string → callers fall back to their existing
    client-card / character-name path (normal sessions untouched)."""
    assert _persona_name_from_params(None) == ""
    assert _persona_name_from_params({}) == ""
    assert _persona_name_from_params({"emotion_preset": "anxious"}) == ""


def test_display_helper_empty_when_persona_name_missing():
    """Defensive: if persona_brief is set but the name failed to propagate, the
    helper returns "" rather than guessing — callers then fall back, and the
    dossier «Кто ты» block (which carries the name) remains the only identity.
    This mirrors the prompt-pin rule («не пиннем чужое имя вовсе»)."""
    assert _persona_name_from_params({"persona_brief": _PERSONA_BRIEF}) == ""
    assert (
        _persona_name_from_params({"persona_brief": _PERSONA_BRIEF, "persona_name": "  "})
        == ""
    )


def test_display_helper_ignores_blank_persona_brief():
    """A blank persona_brief is not a persona session even if a name is present
    — symmetric with the prompt-builder's emptiness check."""
    assert (
        _persona_name_from_params({"persona_brief": "  ", "persona_name": _PERSONA_NAME})
        == ""
    )


# ──────────────────────────────────────────────────────────────────────────
# (D) Name-pin in the LLM prompt — persona name, never the random one
# ──────────────────────────────────────────────────────────────────────────
# The pin is computed inline inside the large async ``_generate_character_reply``
# and is not separately callable without a full WS/session harness. We fence
# its contract at source level (same AST-guard style as the P1 regression and
# the client-domain invariants): on a persona session the pinned name comes
# from custom_params["persona_name"] (the dossier name), NOT from
# state["client_name"] (the random ClientProfile name).


def _generate_character_reply_tree() -> ast.FunctionDef:
    src = inspect.getsource(ws_training._generate_character_reply)
    # Dedent not needed: module-level async def.
    return ast.parse(src).body[0]


def test_name_pin_branches_on_persona_brief():
    """``_generate_character_reply`` must read custom_params['persona_brief'] to
    decide whether the session is persona-driven (the gate for suppressing the
    random ClientProfile name in the pin)."""
    src = inspect.getsource(ws_training._generate_character_reply)
    assert "persona_brief" in src
    assert "persona_name" in src


def test_name_pin_uses_persona_name_not_random_client_name_in_persona_branch():
    """In the persona branch the authoritative name must be sourced from
    custom_params['persona_name'] — NOT from state['client_name'] (the random
    generated identity). We verify the persona branch assigns client_name from
    a persona_name lookup, and that state['client_name'] is only consulted in
    the non-persona (else) branch.

    Pre-P2 FAIL: there was no persona branch — client_name came from
    state['client_name'] unconditionally, pinning the random «Сидоров»."""
    tree = _generate_character_reply_tree()

    persona_name_reads: list[ast.Subscript | ast.Call] = []
    client_name_state_reads = 0

    for node in ast.walk(tree):
        # state.get("client_name") or state["client_name"]
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "get":
            if node.args and isinstance(node.args[0], ast.Constant) and node.args[0].value == "client_name":
                client_name_state_reads += 1
            if node.args and isinstance(node.args[0], ast.Constant) and node.args[0].value == "persona_name":
                persona_name_reads.append(node)

    # The persona branch must look up persona_name at least once.
    assert persona_name_reads, "persona_name is never read — persona name-pin branch is missing"
    # state['client_name'] is still consulted (non-persona path), proving the
    # normal path is intact — but it is no longer the ONLY source.
    assert client_name_state_reads >= 1


def test_language_constraint_always_applied():
    """The Russian-only language constraint must be added for EVERY mode,
    including a persona session where no name is pinned — it was previously
    bundled inside the name-pin block and would have been skipped when the pin
    was empty. (Improvement guard, no regression on normal sessions.)"""
    src = inspect.getsource(ws_training._generate_character_reply)
    assert "_lang_constraint" in src
    # The constraint is concatenated unconditionally (outside the if-name block).
    assert "extra_system = _name_pin + _lang_constraint + extra_system" in src
