FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm ci
RUN npm run db:generate

COPY apps ./apps
COPY src ./src
COPY tsconfig.json vite.config.ts ./

ENV NODE_ENV=production
ENV API_PORT=3001

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate deploy && npx vite-node apps/api/src/server/main.ts"]
